# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Sunny's Tech Note
tagline:          ''
description:      'Life is a marathon not a sprint.'
url:              https://ssjlin9999.github.io/
baseurl:          /
paginate:         5

# About/contact
author:
  name:           'Sunny''s Blog'
  url:            

paginate:         5

# Custom vars
version:          0.1.0

gems:             [jekyll-paginate, jekyll-admin]
github:
  repo:           https://github.com/ssjlin9999
